#!/bin/bash

user="ubuntu"
host="192.168.1.99"
destination="/home/ubuntu/sql_qa/"

rsync -avzh --exclude deploy --exclude .venv --exclude chroma --exclude .git --exclude .vscode --exclude .env --exclude README.md --exclude Chinook.db --exclude docker-compose.yml --exclude Chinook_sqlite.sql --exclude .gitignore --exclude "__pycache__/" . $user@$host:$destination

ssh $user@$host <<ENDSSH
    cd $destination
    sudo docker compose down
    sudo docker compose up -d
    exit
ENDSSH
